/***************************************************************
    *  DO NOT EDIT THIS FILE!
    *         
    *  This file is automatically generated by HP Service Test.
    *  Manually changing the contents of this file may result in 
    *  loss of information.
    *          
    *  To edit the test, open the file ‘GetVorgangItem.st’ 
    *  in HP Service Test.
     ***************************************************************/
    
    namespace Script
    {
    using System;
    using System.Text;
    using System.Threading;
    using System.Xml;
    using System.Xml.Schema;
    using HP.ST.Fwk.ReporterFWK;
    using HP.ST.Shared.Utilities;
    using HP.ST.Ext.BindingImpl.Getters;
    using HP.ST.Ext.BindingImpl.Setters;
    using HP.ST.Fwk.RunTimeFWK.BindingFWK;
    using HP.ST.Fwk.RunTimeFWK.BindingFWK.PropInfo;
    using HP.ST.Fwk.RunTimeFWK.BindingFWK.Getters;
    using HP.ST.Fwk.RunTimeFWK.BindingFWK.Setters;
    using HP.ST.Fwk.RunTimeFWK;
    using HP.ST.Fwk.RunTimeFWK.Utilities;
    using HP.ST.Fwk.RunTimeFWK.HelperClasses;
    using HP.ST.Fwk.RunTimeFWK.CompositeActivities;
    using HP.ST.Ext.BindingImpl.Setters.DataSourceSetters;
    using HP.ST.Fwk.JVMLoader;
    using System.IO;
    using System.Collections.Generic;
    using System.Reflection;
    using HP.ST.Fwk.SOAReplayAPI;
    using HP.ST.Fwk.UFTLicensing;
    
    
    
    public partial class WorkFlowScript : STWorkFlowScriptBase
    {    
    	TestUserCode _userCode = null;
    	TestEntities _flow = null;
    	static Reporter reporter;
    	int reportLevelInTree;
        HP.ST.Fwk.ReportCreator.QTPEngine.QTPEngineReportCreator reportCreator;
    	
    	public BindDirection bind_dir1 = null;
        public BindDirection bind_dir2 = null;
        public BindDirection bind_dir3 = null;
        
        public IEnumerable<FeaturesGroup> LicensedFeatures
        {
        
        get
        {
        List<FeaturesGroup> features = new List<FeaturesGroup>();
        return features;
        
        }
        
        }
        
        public WorkFlowScript()
            : base(VuserClass.CommandLineArguments, new STRunTimeContext(), "test")
        {	
        	UpdateContextWithActionFolder(String.Empty);
        	
        }
        
        public WorkFlowScript(ISTRunTimeContext ctx)
            : base(VuserClass.CommandLineArguments, ctx, "test")
            
        {
        	this._context = ctx;
        	UpdateContextWithActionFolder(String.Empty);
        	UpdateTestSettings(ctx);
        }
        
        internal void InitializeComponent()
        {
        	LoadInput();
        	
        	InitReport();
        	
        	InitializeEncryptionManagerValues();
        
        	_userCode = new TestUserCode();
            _flow = _userCode;
            _flow.Context=this._context;
            
            
        
        	_flow.StartActivity1 = new HP.ST.Ext.BasicActivities.StartActivity(_context,"StartActivity1");
            _flow.Loop2 = new HP.ST.Fwk.RunTimeFWK.CompositeActivities.Loop<Loop2Input>(_context,"Loop2",LoopType.For);
            _flow.EndActivity3 = new HP.ST.Ext.BasicActivities.EndActivity(_context,"EndActivity3");
            _flow.Sequence11 = new HP.ST.Fwk.RunTimeFWK.CompositeActivities.Sequence(_context,"Sequence11");
            _flow.CallSTTest9 = new HP.ST.Ext.STRunnerActivity.RunSTActivity(_context,"CallSTTest9",false);
            _flow.HTTPActivity8 = new HP.ST.Ext.HTTPActivity.HTTPActivity(_context,"HTTPActivity8");
            XmlDocument StartActivity1_ExecutionInputParameters_Document = new XmlDocument();
            StartActivity1_ExecutionInputParameters_Document.PreserveWhitespace = true;
            StartActivity1_ExecutionInputParameters_Document.LoadXml(
@"<Arguments><proxy>http://127.0.0.1:3128</proxy></Arguments>");
            _flow.StartActivity1.ExecutionInputParameters = StartActivity1_ExecutionInputParameters_Document;
            _flow.StartActivity1.Comment = @"";
            _flow.StartActivity1.IconPath = @"AddIns\ServiceTest\BasicActivities\toolbox_code_activity.png";
            _flow.StartActivity1.Name = @"Start";
            _flow.StartActivity1.JVM = new HP.ST.Ext.BasicActivities.JVMProperties();
            _flow.StartActivity1.IsJavaUsed = false;
            _flow.StartActivity1.JVM.Classpath = @"%CLASSPATH%";
            _flow.StartActivity1.JVM.AdditionalVMParameters = @"";
            _flow.StartActivity1.JMS = new HP.ST.Ext.BasicActivities.JMSProperties();
            _flow.StartActivity1.IsJmsUsed = false;
            _flow.StartActivity1.JMS.JNDIContextFactory = @"<Select...>";
            _flow.StartActivity1.JMS.JNDIProviderUrl = @"";
            _flow.StartActivity1.JMS.JMSConnectionFactory = @"";
            _flow.StartActivity1.JMS.SecurityPrincipal = @"";
            _flow.StartActivity1.JMS.SecurityCredentials = @"";
            _flow.StartActivity1.JMS.ConnectionsPerProcess = @"1";
            _flow.StartActivity1.JMS.TimeoutOptions = @"DN_User_defined_Timeout";
            _flow.StartActivity1.JMS.UserTimeout = @"20";
            _flow.StartActivity1.JMS.GenerateAutoSelector = @"No";
            this.Activities.Add (_flow.StartActivity1);
            _flow.Loop2.ConditionAsString = @"Run for 1 iteration";
            _flow.Loop2.NumberOfIterations = (int)1;
            _flow.Loop2.Comment = @"";
            _flow.Loop2.IconPath = @"AddIns\ServiceTest\BasicActivities\toolbox_loop.png";
            _flow.Loop2.Name = @"Test Flow";
            _flow.Loop2.Activities.Add (_flow.Sequence11);
            this.Activities.Add (_flow.Loop2);
            _flow.EndActivity3.Comment = @"";
            _flow.EndActivity3.IconPath = @"AddIns\ServiceTest\BasicActivities\toolbox_code_activity.png";
            _flow.EndActivity3.Name = @"End";
            this.Activities.Add (_flow.EndActivity3);
            _flow.Sequence11.Comment = @"";
            _flow.Sequence11.IconPath = @"";
            _flow.Sequence11.Name = @"Sequence11";
            _flow.Sequence11.Activities.Add (_flow.CallSTTest9);
            _flow.Sequence11.Activities.Add (_flow.HTTPActivity8);
            XmlDocument CallSTTest9_InputProperties_Document = new XmlDocument();
            CallSTTest9_InputProperties_Document.PreserveWhitespace = true;
            CallSTTest9_InputProperties_Document.LoadXml(
@"<Arguments><Proxy>{Step.OutputProperties.StartActivity1.proxy}</Proxy></Arguments>");
            _flow.CallSTTest9.InputProperties = CallSTTest9_InputProperties_Document;
            _flow.CallSTTest9.Comment = @"";
            _flow.CallSTTest9.IconPath = @"AddIns\ServiceTest\STRunner\ictb_api_test_16x16.png";
            _flow.CallSTTest9.Name = @"GetARASOAuth";
            _flow.CallSTTest9.ScriptPath = String.IsNullOrEmpty(_context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallSTTest9.ScriptPath}")) ? @"..\GetARASOAuth" : _context.ResourceManager.GetValue(@"{Step.GeneralProperties.CallSTTest9.ScriptPath}");
            _flow.CallSTTest9.ActionName = @"";
            _flow.CallSTTest9.ResultLocation = @"RunStReport\";
            VTDPropertyInfoBase pi1 = new VTDPropertyInfoBase("ExecutionInputParameters","/*[local-name(.)='Arguments'][1]/*[local-name(.)='proxy'][1]");
            VTDBaseGetter binding_getter1 = new VTDXPathGetter(pi1,XmlTypeCode.String);
            VTDPropertyInfoBase pi2 = new VTDPropertyInfoBase("InputProperties","/*[local-name(.)='Arguments'][1]/*[local-name(.)='Proxy'][1]");
            VTDBaseSetter binding_setter1 = new VTDXPathSetter(pi2,XmlTypeCode.String);
            binding_setter1 = new StringFormaterDecorator(binding_setter1,"{Step.OutputProperties.StartActivity1.proxy}");
            bind_dir1 = new BindDirection(_flow.StartActivity1,binding_getter1,binding_setter1,BindTargetType.ToInProperty);
            _flow.CallSTTest9.InDirections.Add(bind_dir1);
            _flow.HTTPActivity8.TextBody = @"";
            _flow.HTTPActivity8.TextXmlBody = @"";
            _flow.HTTPActivity8.FileBody = @"";
            _flow.HTTPActivity8.PostBody = @"";
            _flow.HTTPActivity8.Url = @"http://80.158.47.39/11SP15_Demo/Server/InnovatorServer.aspx";
            _flow.HTTPActivity8.HttpMethod = @"POST";
            _flow.HTTPActivity8.HttpVersion = @"1.1";
            _flow.HTTPActivity8.RequestHeaders = new Pair<string, string>[5];
            _flow.HTTPActivity8.RequestHeaders[0] = new Pair<string, string>();
            _flow.HTTPActivity8.RequestHeaders[0].Key = @"Authorization";
            _flow.HTTPActivity8.RequestHeaders[0].Value = @"{Step.OutputProperties.CallSTTest9.AccessToken}";
            _flow.HTTPActivity8.RequestHeaders[1] = new Pair<string, string>();
            _flow.HTTPActivity8.RequestHeaders[1].Key = @"Content-Type";
            _flow.HTTPActivity8.RequestHeaders[1].Value = @"text/xml";
            _flow.HTTPActivity8.RequestHeaders[2] = new Pair<string, string>();
            _flow.HTTPActivity8.RequestHeaders[2].Key = @"SOAPAction";
            _flow.HTTPActivity8.RequestHeaders[2].Value = @"ApplyItem";
            _flow.HTTPActivity8.RequestHeaders[3] = new Pair<string, string>();
            _flow.HTTPActivity8.RequestHeaders[3].Key = @"Cache-Control";
            _flow.HTTPActivity8.RequestHeaders[3].Value = @"no-cache";
            _flow.HTTPActivity8.RequestHeaders[4] = new Pair<string, string>();
            _flow.HTTPActivity8.RequestHeaders[4].Key = @"Connection";
            _flow.HTTPActivity8.RequestHeaders[4].Value = @"keep-alive";
            _flow.HTTPActivity8.Comment = @"";
            _flow.HTTPActivity8.IconPath = @"AddIns\ServiceTest\HTTPActivity\toolbox_http.png";
            _flow.HTTPActivity8.RequestBodyType = @"Xml";
            _flow.HTTPActivity8.ResponseType = @"Text";
            _flow.HTTPActivity8.Name = @"GetBMWVorgang";
            _flow.HTTPActivity8.Proxy.Server = @"{Step.OutputProperties.StartActivity1.proxy}";
            _flow.HTTPActivity8.Proxy.Username = @"";
            _flow.HTTPActivity8.Proxy.Password = @"";
            _flow.HTTPActivity8.Authentication.Username = @"";
            _flow.HTTPActivity8.Authentication.Password = @"";
            _flow.HTTPActivity8.Authentication.PreemptiveAuthentication = false;
            _flow.HTTPActivity8.ConnectionType = @"Keep-Alive";
            _flow.HTTPActivity8.Timeout = (int)100000;
            _flow.HTTPActivity8.ClientCertificate.Password = @"";
            _flow.HTTPActivity8.ClientCertificate.FileSystem.Path = @"";
            _flow.HTTPActivity8.UseClientCertificate = false;
            _flow.HTTPActivity8.MaximumAutomaticRedirections = (int)3;
            _flow.HTTPActivity8.AllowRedirections = true;
            _flow.HTTPActivity8.ReuseCookies = true;
            _flow.HTTPActivity8.ExpectServerError = false;
            _flow.HTTPActivity8.HanaRequest = false;
            XmlDocument HTTPActivity8_XMLBody_Document = new XmlDocument();
            HTTPActivity8_XMLBody_Document.PreserveWhitespace = true;
            HTTPActivity8_XMLBody_Document.LoadXml(
@"<SOAP-ENV:Envelope xmlns:SOAP-ENV=""http://schemas.xmlsoap.org/soap/envelope/"">
  <SOAP-ENV:Body>
    <ApplyItem>
      <Item type=""BMW_Vorgang"" action=""get"" select=""_verwendung,_zeitpunkt"" />
    </ApplyItem>
  </SOAP-ENV:Body>
</SOAP-ENV:Envelope>");
            _flow.HTTPActivity8.XMLBody = HTTPActivity8_XMLBody_Document;
            XmlDocument HTTPActivity8_RequestMultipartInfoXml_Document = new XmlDocument();
            HTTPActivity8_RequestMultipartInfoXml_Document.PreserveWhitespace = true;
            HTTPActivity8_RequestMultipartInfoXml_Document.LoadXml(
@"<RequestMultipartInfo><Type>Related</Type></RequestMultipartInfo>");
            _flow.HTTPActivity8.RequestMultipartInfoXml = HTTPActivity8_RequestMultipartInfoXml_Document;
            _flow.HTTPActivity8.Multipart=false;
            VTDPropertyInfoBase pi3 = new VTDPropertyInfoBase("OutputProperties","/*[local-name(.)='Arguments'][1]/*[local-name(.)='AccessToken'][1]");
            VTDBaseGetter binding_getter2 = new VTDXPathGetter(pi3,XmlTypeCode.String);
            VTDPropertyInfoBase pi4 = new VTDPropertyInfoBase("RequestHeaders[0].Value");
            VTDBaseSetter binding_setter2 = new VTDObjectSetter(pi4);
            binding_setter2 = new StringFormaterDecorator(binding_setter2,"{Step.OutputProperties.CallSTTest9.AccessToken}");
            bind_dir2 = new BindDirection(_flow.CallSTTest9,binding_getter2,binding_setter2,BindTargetType.ToInProperty);
            _flow.HTTPActivity8.InDirections.Add(bind_dir2);
            VTDPropertyInfoBase pi5 = new VTDPropertyInfoBase("ExecutionInputParameters","/*[local-name(.)='Arguments'][1]/*[local-name(.)='proxy'][1]");
            VTDBaseGetter binding_getter3 = new VTDXPathGetter(pi5,XmlTypeCode.String);
            VTDPropertyInfoBase pi6 = new VTDPropertyInfoBase("Proxy.Server");
            VTDBaseSetter binding_setter3 = new VTDObjectSetter(pi6);
            binding_setter3 = new StringFormaterDecorator(binding_setter3,"{Step.OutputProperties.StartActivity1.proxy}");
            bind_dir3 = new BindDirection(_flow.StartActivity1,binding_getter3,binding_setter3,BindTargetType.ToInProperty);
            _flow.HTTPActivity8.InDirections.Add(bind_dir3);
            XmlDocument HTTPActivity8_ExpectedResponseXmlBody_Document = new XmlDocument();
            HTTPActivity8_ExpectedResponseXmlBody_Document.PreserveWhitespace = true;
            HTTPActivity8_ExpectedResponseXmlBody_Document.LoadXml(
@"<F6DA54ED-92F5-4c5c-9795-170905F25080 />");
            _flow.HTTPActivity8.ExpectedResponseXmlBody = HTTPActivity8_ExpectedResponseXmlBody_Document;
            XmlDocument HTTPActivity8_ExpectedResponseJsonBody_Document = new XmlDocument();
            HTTPActivity8_ExpectedResponseJsonBody_Document.PreserveWhitespace = true;
            HTTPActivity8_ExpectedResponseJsonBody_Document.LoadXml(
@"<F6DA54ED-92F5-4c5c-9795-170905F25080 />");
            _flow.HTTPActivity8.ExpectedResponseJsonBody = HTTPActivity8_ExpectedResponseJsonBody_Document;
            XmlDocument HTTPActivity8_ExpectedOutputProperties_Document = new XmlDocument();
            HTTPActivity8_ExpectedOutputProperties_Document.PreserveWhitespace = true;
            HTTPActivity8_ExpectedOutputProperties_Document.LoadXml(
@"<Arguments><ResponseHttpVersion /><StatusCode /><StatusDescription /><ResponseBody /><ResponseBodyAsBase64 /></Arguments>");
            _flow.HTTPActivity8.ExpectedOutputProperties = HTTPActivity8_ExpectedOutputProperties_Document;
            
        }
        
        internal void InitializeEncryptionManagerValues()
        {
        
        }
        	
    	bool useReport = true;
    
    	protected override STExecutionResult ExecuteStep()
        {
            return base.ExecuteStep();
        }
    
        public void Start()
        {
    	    try
    		{
    		  Workflow_Executing();
    		  this.ExecuteStep();
    		}
    		finally
    		{
    		  WorkFlowScript_Completed();
    		}
        }
    
    	private void InitReport()
    	{
    		if (useReport)
    		{	
    			// Intialize Reporter
    			string reportDBDir = Path.Combine(this._context.ReportDirectory, @"Report");
    			CleanupReport(reportDBDir);        	
    			string reportDBPath = Path.Combine(reportDBDir, "VTDReport.mdb");        	
    			if (reporter == null)
    			{
    				reporter = new Reporter(reportDBPath);
    			}
    			_context.Reporter = reporter;
    		}
    	}
    
        public static void CopyDirectory(string Src, string Dst)
        {
            String[] Files;
    
            if (Dst[Dst.Length - 1] != Path.DirectorySeparatorChar)
                Dst += Path.DirectorySeparatorChar;
            if (!Directory.Exists(Dst)) Directory.CreateDirectory(Dst);
            Files = Directory.GetFileSystemEntries(Src);
            foreach (string Element in Files)
            {
                // Sub directories
                if (Directory.Exists(Element))
                    CopyDirectory(Element, Dst + Path.GetFileName(Element));
                // Files in directory
                else
                    File.Copy(Element, Dst + Path.GetFileName(Element), true);
            }
        }
        
        private void CleanupReport(string reportDBDir)
        {   
    		if (useReport)
    		{             
    			string reportTemplateDir = Path.Combine(ServiceTestRunner.GetInstallPath(),@"bin\ReportResources");                
    			try
    			{
            		CopyDirectory(reportTemplateDir, reportDBDir);
    			}
    			catch //(Exception ex)
    			{
    				//ToDo: LoggingService.Warn("Report Cleanup Error", ex);
    			}
    		}
        }
    
        void Workflow_Executing()
        {   
        	InitReportNode();
                       
        }
    
    	private void InitReportNode()
    	{
    		if (useReport)
    		{	
        		// Init report creator
    			this.reportCreator = new HP.ST.Fwk.ReportCreator.QTPEngine.QTPEngineReportCreator();
    			this.reportLevelInTree = reportCreator.Init(_context.EnvironmentProfile.GetVariableValue("TestName"), _context);
                
    			STActivityBase activity = this;
    			string workflowID = activity.GetHashCode().ToString();
    			ReportNodeCreationData newNodeData =
    			new ReportNodeCreationData(workflowID, workflowID, DateTime.Now);
    			reporter.CreateReportNode(newNodeData);
            
    			ReportInfoData newReportData = new ReportInfoData(workflowID, ReportKeywords.TypeKeywordTag, this.GetType().ToString());
    			reporter.SendReportData(newReportData);
    			newReportData = new ReportInfoData(workflowID, ReportKeywords.NameKeywordTag, this.Name);
    			//TrackData(ReportInfoData.InfoDataTag, newReportData);
    			reporter.SendReportData(newReportData);            
            }
    	}
        
        void WorkFlowScript_Completed()
        {   
    		
    
    		CreateReportFiles();
    					
        	// Write all snapshots to disk
    		this._context.SnapshotManager.WriteSnapshotsToDisk();
    
    		OnExecutionCompleted();
    		
        }
    
    	private void CreateReportFiles()
    	{
    		if (useReport)
    		{	
    			//Dispose reporter inorder to close connection to report DB
           		this._context.Reporter.Dispose();
            	
           		// Run report creator
    			reportCreator.RunOnDBAndCreateFiles();
    		}
    	}
    
        
        void Workflow_Faulting()
        {
    		
    
    		CreateReportFiles();
            // Write all snapshots to disk
    		this._context.SnapshotManager.WriteSnapshotsToDisk();
           
    		OnExecutionCompleted();
        }
    
    	protected override QcSystemVariables GetRuntimeQcVariables(ISTRunTimeContext context)
    	{
    		return new HP.ST.Ext.BasicActivities.RuntimeQcVariables(this._context);
    	}
            
    	protected override TestSystemVariables GetTestSystemVariables(ISTRunTimeContext context)
    	{
    		return new HP.ST.Ext.BasicActivities.RuntimeTestVariables(this._context);
    	}
    
    	private void UpdateTestSettings(ISTRunTimeContext ctx)
        {
    		ctx.PropertyBag["StopTestOnStepFailure"] = true;
    	}
    }
    
    public partial class VuserClass
    {
    	public static string[] CommandLineArguments;
    	public static string[] DotNetResolverPaths;
    	
        public VuserClass()
        {
    				
    		AssemblyResolver.AddSTPathsToResolutionPaths();
    		AssemblyResolver.AttachToAppdomain();
        }
    
        private void AddAssemblyResolver()
        {
    		AssemblyResolver.AddTestPathToResolutionPaths(GetTestPath());
    		AssemblyResolver.AddPathsForAssemblyResolution(DotNetResolverPaths);
        }
    	
        public int STAction()
        {	
            AddAssemblyResolver();
            STRunTimeContext ctx = new STRunTimeContext(Directory.GetParent(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location)).FullName, string.Empty);
            WorkFlowScript script = new WorkFlowScript(ctx);
            script.InitializeComponent();
            script.Start();       
            
            return 0;
        }
        
        public void NotifyLicenseException(string msg)
        {
        		
    		try
    		{
    		    STRunTimeContext ctx = new STRunTimeContext(Directory.GetParent(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location)).FullName, string.Empty);
                WorkFlowScript script = new WorkFlowScript(ctx);
                script.InitializeComponent();
                script.Context.ReplayClient.OnLicenseFailure(msg);
                
            }
            catch (Exception)
            {
    			// ToDo: log the error message
            }        
        }
    
    	 protected string GetTestPath()
            {
                if (CommandLineArguments != null)
                {
                    for (int i = 0; i < CommandLineArguments.Length; i++)
                    {
                        if (CommandLineArguments[i].Equals("-test", StringComparison.OrdinalIgnoreCase))
                        {
                            return CommandLineArguments[i + 1];
                        }
                    }
                }
                return String.Empty;
            }
        
    }
    
    }
    